---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-desktop
  namespace: novnc
spec:
  selector:
    matchLabels:
      app: remote-desktop
  template:
    metadata:
      labels:
        app: remote-desktop
    spec:
      containers:
      - name: remote-desktop
        image: fredblgr/ubuntu-novnc:22.04
        env:
        - name: "HTTP_PASSWORD"
          value: "demopass123"
        - name: "RESOLUTION"
          value: "1920x1080"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "8000Mi"
            cpu: "4000m"
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: remote-desktop-service
  namespace: novnc
spec:
  selector:
    app: remote-desktop
  ports:
    - protocol: TCP
      port: 6080
      targetPort: 80

