apiVersion: v1
kind: Namespace
metadata:
  name: onboardme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboardme
  namespace: onboardme
spec:
  selector:
    matchLabels:
      app: onboardme
  template:
    metadata:
      labels:
        app: onboardme
    spec:
      containers:
      - name: onboardme
        image: ubuntu:latest
        command: ["/bin/bash"]
