apiVersion: v1
kind: Namespace
metadata:
  name: onboardme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onboardme
  namespace: onboardme
spec:
  selector:
    matchLabels:
      app: onboardme
  template:
    metadata:
      labels:
        app: onboardme
    spec:
      containers:
      - name: onboardme
        image: jessebot/onboardme:debian12
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: onboardme-svc
  namespace: onboardme
spec:
  selector:
    app: onboardme
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 22
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onboardme-ingress
  namespace: onboardme
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - onboardme.buildstar.online
      secretName: "onboardme-tls"
  rules:
  - host: onboardme.buildstar.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onboardme
            port:
              number: 5000
