---
# webapp is deployed LAST because we need secrets and persistent volumes up 1st
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://github.com/cloudymax/argocd-nvidia-lab.git
    path: templates/
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
