# Helm Values:
# https://github.com/zalando/postgres-operator/blob/master/charts/postgres-operator-ui/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgoperator-ui
spec:
  destination:
    namespace: postgres-operator
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: >-
      https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
    targetRevision: 1.10.0
    chart: postgres-operator-ui
    helm:
      skipCrds: true
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/issuer: "letsencrypt-staging"
            kubernetes.io/tls-acme: "true"           
          hosts:
            - host: pg-operator.cloudydev.net
              paths: ["/"]
          tls:
            - secretName: pg-operator-tls
              hosts:
                - pg-operator.cloudydev.net
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
