---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogIm5naW54LWluZ3Jlc3MiCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSB0YXJnZXRzOiBbImluZ3Jlc3MtbmdpbngtY29udHJvbGxlci1tZXRyaWNzLmluZ3Jlc3Mtbmdpbnguc3ZjLmNsdXN0ZXIubG9jYWw6MTAyNTQiXQotIGpvYl9uYW1lOiAibnZpZGlhLXNtaSIKICBzdGF0aWNfY29uZmlnczoKICAtIHRhcmdldHM6IFsibnZpZGlhLWRjZ20tZXhwb3J0ZXIuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo5NDAwIl0K
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
