---
apiVersion: v1
kind: Service
metadata:
  name: cdi-uploadproxy-service
  namespace: cdi
  labels:
    cdi.kubevirt.io: "cdi-uploadproxy"
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    cdi.kubevirt.io: cdi-uploadproxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cdi-uploadproxy-ingress
  namespace: cdi
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - kubevirt-cdi.buildstar.online
      secretName: "letsencrypt-prod"
  rules:
  - host: kubevirt-cdi.buildstar.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cdi-uploadproxy-service
            port:
              number: 5000
