---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  monitorNamespace: monitoring
  monitorAccount: prometheus-helm-chart-kube-prometheus
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - clientPassthrough
        - SnapshotGate
        - CPUNodeDiscoveryGate
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
