---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  monitorNamespace: monitoring
  monitorAccount: prometheus-helm-chart-kube-prometheus
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - CPUManager
        - GPU
        - HostDevices
        - VMExport
        - HotplugVolumes
        - HostDisk
        - Macvtap
        - Passt
        - HotplugNICs
        - clientPassthrough
        - Snapshot
        - CPUNodeDiscovery
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
