---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "lunar"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    cdi.kubevirt.io/storage.import.endpoint: "https://cloud-images.ubuntu.com/lunar/current/lunar-server-cloudimg-amd64.img"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
