---
# namespace for isolation
apiVersion: v1
kind: Namespace
metadata:
  name: windows10
---
# Expose RDP port via a loadbalancer
kind: Service
apiVersion: v1
metadata:
  name: windows10-rdp-lb
  namespace: windows10
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: rdp
      protocol: TCP
      port: 3389
      targetPort: 3389
  type: LoadBalancer
  selector:
    kubevirt.io/domain: windows10
---
# This will be the disk we install windows on from the ISO
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windows10-hdd-pvc
  namespace: windows10
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows10-vm
  namespace: windows10
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: windows10
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        features:
          smm: {}
          kvm: {}
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            spinlocks:
              spinlocks: 8191
            vapic: {}
        firmware:
          bootloader:
            efi: {}
        cpu:
          model: host-passthrough
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 2
            disk:
              bus: virtio
            name: harddrive
          - bootOrder: 3
            cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: windows10-iso-pvc
      - name: harddrive
        persistentVolumeClaim:
          claimName: windows10-hdd-pvc
      - containerDisk:
          image: quay.io/kubevirt/virtio-container-disk:v1.0.0-rc.1-amd64
        name: virtiocontainerdisk
