apiVersion: v1
kind: Namespace
metadata:
  name: nginx-hello-rollout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello-rollout-blue
  namespace: nginx-hello-rollout
spec:
  selector:
    matchLabels:
      app: nginx-hello-rollout-blue
  template:
    metadata:
      labels:
        app: nginx-hello-rollout-blue
    spec:
      containers:
      - name: nginx-hello-rollout-blue
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-hello-rollout-blue-service
  namespace: nginx-hello-rollout
spec:
  selector:
    app: nginx-hello
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-hello-rollout-blue-ingress
  namespace: nginx-hello-rollout
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - nginx-hello.cloudydev.net
      secretName: "nginx-hello-rollout-tls"
  rules:
  - host: nginx-hello.cloudydev.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-hello-service
            port:
              number: 5000
