apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
        - image: deserializeme/knative
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
