---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogIm5naW54LWluZ3Jlc3MiCiAgc3RhdGljX2NvbmZpZ3M6CiAgLSB0YXJnZXRzOiBbImluZ3Jlc3MtbmdpbngtY29udHJvbGxlci1tZXRyaWNzLmluZ3Jlc3Mtbmdpbnguc3ZjLmNsdXN0ZXIubG9jYWw6MTAyNTQiXQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: additional-scrape-configs
  namespace: monitoring
