---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-addons
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/cloudymax/argocd-nvidia-lab.git
    path: argo-addons/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-rollouts
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
