---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gamesonwhales
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/cloudymax/argocd-nvidia-lab.git
    path: games-on-whales/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gamesonwhales
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
