---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: novnc-desktop
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/cloudymax/argocd-nvidia-lab.git
    path: desktops/novnc/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: novnc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
