# https://github.com/zalando/postgres-operator
# Postgres operator creates and manages PostgreSQL clusters running in Kubernetes 
# https://postgres-operator.readthedocs.io/
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/cloudymax/argocd-nvidia-lab.git
    path: postgres-operator/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgres-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
