---
apiVersion: instancetype.kubevirt.io/v1alpha2
kind: Virtualmachineclusterinstancetypes
metadata:
  name: mini-standard
spec:
  cpu:
    guest: 1
  memory:
    guest: 2Gi
---
apiVersion: instancetype.kubevirt.io/v1alpha2
kind: Virtualmachineclusterinstancetypes
metadata:
  name: small-standard
spec:
  cpu:
    guest: 2
  memory:
    guest: 4Gi
---
apiVersion: instancetype.kubevirt.io/v1alpha2
kind: Virtualmachineclusterinstancetypes
metadata:
  name: medium-standard
spec:
  cpu:
    guest: 4
  memory:
    guest: 8Gi
---
apiVersion: instancetype.kubevirt.io/v1alpha2
kind: Virtualmachineclusterinstancetypes
metadata:
  name: large-standard
spec:
  cpu:
    guest: 8
  memory:
    guest: 16Gi
