---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgl
  template:
    metadata:
      labels:
        app: xgl
    spec:
      hostname: xgl
      hostNetwork: true
      containers:
        - name: xgl
          image: ghcr.io/selkies-project/nvidia-glx-desktop:latest
          securityContext:
            allowPrivilegeEscalation: true
          env:
            - name: TZ
              value: UTC
            - name: SIZEW
              value: "1920"
            - name: SIZEH
              value: "1080"
            - name: REFRESH
              value: "60"
            - name: DPI
              value: "96"
            - name: CDEPTH
              value: "24"
            - name: VIDEO_PORT
              value: DFP
            - name: PASSWD
              value: mypasswd
            - name: WEBRTC_ENCODER
              value: nvh264enc
            - name: WEBRTC_ENABLE_RESIZE
              value: "false"
            - name: ENABLE_AUDIO
              value: "true"
            - name: ENABLE_BASIC_AUTH
              value: "false"
          stdin: true
          tty: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 64Gi
              cpu: "16"
              nvidia.com/gpu: 1
            requests:
              memory: 100Mi
              cpu: 100m
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /cache
              name: xgl-cache-vol
            - mountPath: /home/user
              name: xgl-root-vol
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: xgl-cache-vol
          emptyDir: {}
        - name: xgl-root-vol
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: glx-service
spec:
  selector:
    app: xgl
  ports:
    - port: 5431
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glx-ingress
  namespace: glx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/auth-signin: "https://vouch.buildstar.online/login?url=$scheme://$http_host$request_uri&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err"
    nginx.ingress.kubernetes.io/auth-url: https://vouch.buildstar.online/validate
    nginx.ingress.kubernetes.io/auth-response-headers: X-Vouch-User
    nginx.ingress.kubernetes.io/auth-snippet: |
      auth_request_set $auth_resp_jwt $upstream_http_x_vouch_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_vouch_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_vouch_failcount;  
spec:
  tls:
    - hosts:
        - glx.buildstar.online
      secretName: glx-tls
  rules:
    - host: glx.buildstar.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glx-service
                port:
                  number: 5431
