kind: Service
apiVersion: v1
metadata:
  name: console-np-service
  namespace: kube-system
spec:
  selector:
    app: console
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
